/*
auto-generated by: https://github.com/pmndrs/gltfjsx
author: Oziry (https://sketchfab.com/Oziry)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/df95d3da67aa4c769ec81394e0b0ffef
title: Asteroid 01
*/
import React, { useRef, useState } from 'react';
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei/useGLTF';
import { useFrame } from 'react-three-fiber';

export default function Asteroids({ speed, factor, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/scene.gltf');

  function random(min, max) {
    return min + Math.random() * (max - min);
  }

  const [mixer] = useState(() => new THREE.AnimationMixer());

  useFrame((state, delta) => {
    group.current.rotation.y +=
      Math.sin((delta * factor) / 2) * Math.cos((delta * factor) / 2) * 1.5;
    mixer.update(delta * speed);
  });

  const scale = random(0.05, 0.5);

  return (
    <group ref={group} dispose={null}>
      <scene name="Scene" {...props}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[scale, scale, scale]}
            >
              <mesh
                rotation={[1.5707964611537577, 0, 0]}
                material={materials.Asteroid_01}
                geometry={nodes.Asteroid_Mob_01_Asteroid_01_0.geometry}
              />
            </group>
          </group>
        </group>
      </scene>
    </group>
  );
}
