export { default as ComingSoon } from './ComingSoon';
export { default as ContactMe } from './ContactMe';
export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as NewReading } from './NewReading';
export { default as Projects } from './Projects';
export { default as Section } from './Section';
export { default as Skills } from './Skills';
export { default as Work } from './Work';
